paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos
      tags:
       - Produts
      responses: 
       "200":
        description: Los productos fureron obtenidos satisfactoriamente de la base de datos
       "500":
        description: Error interno del servidor usualmente generado por una query defectuosa o un fallo de conexión con la base de datos
