const EErrors = {
  ROUTING_ERROR: 1,
  INVALID_TYPES_ERROR:2,
  DATABASE_ERROR:3,
  AUTHENTICATION_ERROR:4,
  VALIDATION_ERROR:5,
  NOT_FOUND_ERROR: 6,
  INTERNAL_ERROR: 7,
  PASSWORDS_DO_NOT_MATCH: 8,
  USER_NOT_EXIST: 9,
}

module.exports = EErrors